# Generated by Django 6.0.6 on 2026-07-02 13:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Múltipla escolha'), ('multi_answer', 'Resposta múltipla'), ('true_false', 'Verdadeiro ou falso'), ('written', 'Resposta escrita'), ('ordering', 'Ordenar elementos'), ('matching', 'Relacionar colunas'), ('flashcard', 'Flashcard')], editable=False, max_length=20)),
                ('statement', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('explanation', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.question')),
                ('front', models.TextField()),
                ('back', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('exams.question',),
        ),
        migrations.CreateModel(
            name='MatchingQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.question')),
            ],
            options={
                'abstract': False,
            },
            bases=('exams.question',),
        ),
        migrations.CreateModel(
            name='MultiAnswerQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.question')),
            ],
            options={
                'abstract': False,
            },
            bases=('exams.question', models.Model),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.question')),
            ],
            options={
                'abstract': False,
            },
            bases=('exams.question', models.Model),
        ),
        migrations.CreateModel(
            name='OrderingQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.question')),
            ],
            options={
                'abstract': False,
            },
            bases=('exams.question',),
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.question')),
                ('correct_answer', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('exams.question',),
        ),
        migrations.CreateModel(
            name='WrittenQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.question')),
                ('expected_answer', models.CharField(max_length=500)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('accepted_alternatives', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
            bases=('exams.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(max_length=255)),
                ('right', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='exams.matchingquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exams.orderingquestion')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
