# Generated by Django 6.0.6 on 2026-07-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test',
            new_name='exam',
        ),
    ]
