# Generated by Django 6.0.6 on 2026-07-04 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_test_question_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='flashcardquestion',
            name='back',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='flashcardquestion',
            name='front',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='left',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='right',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orderingitem',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='writtenquestion',
            name='expected_answer',
            field=models.CharField(max_length=255),
        ),
    ]
