# Generated by Django 6.0.6 on 2026-06-24 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Múltipla escolha'), ('multi_answer', 'Resposta múltipla'), ('true_false', 'Verdadeiro ou falso'), ('written', 'Resposta escrita'), ('ordering', 'Ordenar elementos'), ('matching', 'Relacionar colunas'), ('flashcard', 'Flashcard')], max_length=20)),
                ('statement', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('explanation', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests_app.test')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['order'],
            },
        ),
    ]
